version: '2'

services:
  certbot:
    image: certbot/certbot
    # command: certonly --help all
    command: certonly -n --agree-tos --email $EMAIL --standalone -d $DOMAIN
    volumes:
      - certs:/etc/letsencrypt/live/$DOMAIN
    ports:
      - "443:443"
      - "83:80"

volumes:
  certs:
